default:
  collection: teaa
  collection_desc: To Enter Africa From America

threads: 20
development:
  es_path: https://cdrhdev1.unl.edu/elastic
  es_index: cdrhapidev-v1
  site_url: https://cdrhdev1.unl.edu/teaa
production:
  es_path: https://cdrhapi.unl.edu/elastic
  es_index: cdrhapi-v1

# this is for generating plain text files per Katrina's request
# run with `post -x html -e text`
text:
  tei_html_xsl: scripts/overrides/tei_to_text.xsl
