default:
  collection: teaa
  collection_desc: To Enter Africa From America

threads: 20
development:
  es_path: https://cdrhdev1.unl.edu/elastic
  es_index: cdrhapidev-v1
production:
  es_path: https://cdrhapi.unl.edu/elastic
  es_index: cdrhapi-v1
