default:
  collection: teaa
  collection_desc: To Enter Africa From America
  tei_html_xsl: scripts/overrides/tei_to_html.xsl
  variables_html:
    image_large: 1200
    image_thumb: 120

threads: 20
development:
  es_path: https://servername.unl.edu/elastic
  es_index: cdrhapidev-v2
  site_url: https://servername.unl.edu/teaa
  media_base: https://servername.unl.edu
  data_base: https://servername.unl.edu/media
  
production:
  site_url: https://africafromamerica.unl.edu
  es_path: https://cdrhapi.unl.edu/elastic
  es_index: cdrhapi-v2

# this is for generating plain text files per Katrina's request
# run with `post -x html -e text`
text:
  tei_html_xsl: scripts/overrides/tei_to_text.xsl
